apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microservice-1-logs-pvc
  namespace: microservice-1
  labels:
    app: microservice-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
