apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: api-gateway
  labels:
    app: api-gateway
    tier: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2  # 최소 2개 파드 유지 (고가용성)
  maxReplicas: 5  # 최대 5개 파드까지 확장 가능 (로컬 환경 고려)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # 70% CPU 사용률에서 스케일링
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # 80% 메모리 사용률에서 스케일링
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # 1분 안정화 시간
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60  # 1분마다 최대 현재 파드 수의 100%까지 증가
    scaleDown:
      stabilizationWindowSeconds: 300  # 5분 안정화 시간
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120  # 2분마다 최대 25%까지 감소 