apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: api-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway-role
  namespace: api-gateway
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-rolebinding
  namespace: api-gateway
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: api-gateway
roleRef:
  kind: Role
  name: api-gateway-role
  apiGroup: rbac.authorization.k8s.io
---
# 다른 네임스페이스의 서비스를 발견하기 위한 ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-gateway-discovery-role
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-gateway-discovery-rolebinding
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: api-gateway
roleRef:
  kind: ClusterRole
  name: api-gateway-discovery-role
  apiGroup: rbac.authorization.k8s.io 
