apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microservice-2-logs-pvc
  namespace: microservice-2
  labels:
    app: microservice-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # 로컬 환경이므로 작은 크기로 설정 
