server:
  port: 5002
  tomcat:
    mbeanregistry:
      enabled: true

spring:
    profiles:
        default: local

    application:
        name: microservice-2
    
    config:
        import:
            - security/application-db.yml

management:
    server:
        port: 6000
    endpoints:
        web:
          exposure:
            include: health,info,prometheus
    endpoint:
        health:
          show-details: always
    prometheus:
      metrics:
        export:
          enabled: true
    metrics:
      tags:
        application: ${spring.application.name}
